### ISSUE TITLE
Make test suite + travis ci integration

### ISSUE THREAD

**Issue by JohnPaton** [RUrlus/afinipy#2]
need to write simple package to test the functionality against. Should contain all sorts of weird import situations

Also, test on windows!

**Comment by JohnPaton** [comment]
You could do integration tests with just string comparison since you know what the output `__init__` of your example is supposed to be

**Comment by RUrlus** [comment]
Tests have been written, see aa044ba67c41a9bd05bdf3cb38acf6e7c82f8650.
Travis CI was also done, which went very smoothly /s. See a lot of commits that followed

**Comment by JohnPaton** [comment]
Haha, very familire . -glad you got it up and running! It will make life less painful in the long run :)
